// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace DemoPerformance
{
    [DbContext(typeof(ProductContext))]
    public partial class ProductContextModel : RuntimeModel
    {
        static ProductContextModel()
        {
            var model = new ProductContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ProductContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
