// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    public partial class ShopDatabaseContextModel
    {
        partial void Initialize()
        {
            var brand = BrandEntityType.Create(this);
            var price = PriceEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productGroup = ProductGroupEntityType.Create(this);
            var review = ReviewEntityType.Create(this);
            var reviewer = ReviewerEntityType.Create(this);
            var specification = SpecificationEntityType.Create(this);
            var specificationDefinition = SpecificationDefinitionEntityType.Create(this);
            var consumerReview = ConsumerReviewEntityType.Create(this, review);
            var expertReview = ExpertReviewEntityType.Create(this, review);
            var webReview = WebReviewEntityType.Create(this, review);

            PriceEntityType.CreateForeignKey1(price, product);
            ProductEntityType.CreateForeignKey1(product, brand);
            ProductEntityType.CreateForeignKey2(product, productGroup);
            ReviewEntityType.CreateForeignKey1(review, product);
            ReviewEntityType.CreateForeignKey2(review, reviewer);
            SpecificationEntityType.CreateForeignKey1(specification, product);
            SpecificationDefinitionEntityType.CreateForeignKey1(specificationDefinition, productGroup);

            BrandEntityType.CreateAnnotations(brand);
            PriceEntityType.CreateAnnotations(price);
            ProductEntityType.CreateAnnotations(product);
            ProductGroupEntityType.CreateAnnotations(productGroup);
            ReviewEntityType.CreateAnnotations(review);
            ReviewerEntityType.CreateAnnotations(reviewer);
            SpecificationEntityType.CreateAnnotations(specification);
            SpecificationDefinitionEntityType.CreateAnnotations(specificationDefinition);
            ConsumerReviewEntityType.CreateAnnotations(consumerReview);
            ExpertReviewEntityType.CreateAnnotations(expertReview);
            WebReviewEntityType.CreateAnnotations(webReview);

            AddAnnotation("ProductVersion", "6.0.9");
            AddAnnotation("Relational:DefaultSchema", "Core");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
