// <auto-generated />
using ACME.DataLayer.Repository.SqlServer;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    [DbContext(typeof(ShopDatabaseContext))]
    public partial class ShopDatabaseContextModel : RuntimeModel
    {
        static ShopDatabaseContextModel()
        {
            var model = new ShopDatabaseContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ShopDatabaseContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
